# Generated by Django 5.2.6 on 2025-09-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Уникальный код страны (например, 'US' для США или 'RU' для России).", max_length=20, unique=True, verbose_name='Код страны')),
                ('name', models.CharField(help_text="Полное название страны (например, 'США' или 'Россия').", max_length=100, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': '🗺️ Страна',
                'verbose_name_plural': '🗺️ Страны',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='country_code_idx'), models.Index(fields=['name'], name='country_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='CyberXXBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название, введенное в Father Bot, для идентификации бота', max_length=255, verbose_name='Название бота')),
                ('username', models.CharField(help_text='Уникальный username, созданный в Father Bot', max_length=255, unique=True, verbose_name='Username бота')),
                ('api_key', models.CharField(help_text='Уникальный API-ключ, выданный при создании бота в Father Bot', max_length=255, unique=True, verbose_name='API ключ бота')),
                ('base_url', models.URLField(help_text='Ссылка трекера на продукт, которая открывается у пользователя при активации бота', max_length=5000, verbose_name='Базовая ссылка')),
                ('pwa_description_url', models.URLField(blank=True, help_text='Ссылка, которая открывает PWA', max_length=1000, null=True, verbose_name='Ссылка на PWA')),
                ('pwa_open_delay', models.IntegerField(default=10, verbose_name='Время до открытия PWA (секунды)')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('process_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '🌍 Телеграм Бот',
                'verbose_name_plural': '🌍 Боты',
                'ordering': ['-created_at', 'username'],
                'indexes': [models.Index(fields=['username'], name='idx_username'), models.Index(fields=['api_key'], name='idx_api_key'), models.Index(fields=['active'], name='idx_active')],
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Уникальный ключ настройки.', max_length=255, unique=True, verbose_name='Переменная')),
                ('value', models.TextField(help_text='Значение настройки.', verbose_name='Значение')),
                ('description', models.CharField(blank=True, help_text='Описание настройки, для чего она предназначена.', max_length=255, null=True, verbose_name='Для чего')),
            ],
            options={
                'verbose_name': '⚙️ Настройки',
                'verbose_name_plural': '⚙️ Настройки',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='idx_key')],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_type', models.CharField(choices=[('basic', 'Базовый'), ('custom', 'Кастомный')], default='basic', help_text="Выберите тип лендинга: 'Базовый' или 'Кастомный'.", max_length=10, verbose_name='Тип лендинга')),
                ('name', models.CharField(help_text='Введите название лендинга.', max_length=255, verbose_name='Название')),
                ('subscriber_count', models.CharField(blank=True, help_text='Введите количество подписчиков (опционально).', max_length=50, null=True, verbose_name='К-во подписчиков')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание лендинга (опционально).', null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, help_text='Введите текст, который будет отображаться на кнопке (опционально).', max_length=100, null=True, verbose_name='Название кнопки')),
                ('logo', models.ImageField(help_text='Загрузите логотип для бота (опционально).', upload_to='logos/', verbose_name='Логотип бота')),
                ('custom_html_file', models.FileField(blank=True, help_text='Загрузите HTML файл для кастомного лендинга (обязательно для кастомного типа).', null=True, upload_to='custom_landings/', verbose_name='HTML файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания лендинга.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления лендинга.', verbose_name='Дата обновления')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Идентификатор Google Analytics для отслеживания.', max_length=20, null=True, verbose_name='Google Analytics ID')),
                ('yandex_metrika_id', models.CharField(blank=True, help_text='Идентификатор Яндекс.Метрики для отслеживания.', max_length=20, null=True, verbose_name='Яндекс.Метрика ID')),
                ('google_analytics_full_script', models.TextField(blank=True, help_text='Полный код скрипта для Google Analytics, если требуется настроить кастомно.', null=True, verbose_name='Полный скрипт Google Analytics')),
                ('yandex_metrika_full_script', models.TextField(blank=True, help_text='Полный код скрипта для Яндекс.Метрики, если требуется настроить кастомно.', null=True, verbose_name='Полный скрипт Яндекс.Метрики')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='aurenora.cyberxxbot', verbose_name='Бот')),
                ('bots', models.ManyToManyField(help_text='Выберите ботов, связанных с этим лендингом.', limit_choices_to={'active': True}, related_name='landings', to='aurenora.cyberxxbot', verbose_name='Боты')),
                ('language', models.ForeignKey(blank=True, help_text='Выберите язык лендинга (если применимо).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurenora.country', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Лендинг',
                'verbose_name_plural': 'Лендинги',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['bot', 'landing_type'], name='idx_bot_landing_type'), models.Index(fields=['name'], name='idx_name')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('city', models.CharField(blank=True, help_text='Город пользователя.', max_length=100, null=True, verbose_name='Город')),
                ('timezone', models.CharField(blank=True, help_text="Таймзона пользователя (например, 'UTC+3').", max_length=50, null=True, verbose_name='Таймзона')),
                ('cyber_link', models.URLField(blank=True, help_text='Ссылка, которая будет открываться при нажатии на кнопку.', max_length=5000, null=True, verbose_name='Ссылка для кнопки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurenora.cyberxxbot', verbose_name='Бот')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurenora.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Временные данные пользователя',
                'verbose_name_plural': 'Временные данные пользователей',
                'indexes': [models.Index(fields=['ip_address'], name='tempdata_idx_ip_address'), models.Index(fields=['country'], name='tempdata_idx_country'), models.Index(fields=['bot'], name='tempdata_idx_bot'), models.Index(fields=['created_at'], name='tempdata_idx_created_at')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(blank=True, help_text='Уникальный идентификатор пользователя в Telegram.', max_length=50, null=True, verbose_name='Telegram user id')),
                ('node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=100, null=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, help_text='Полное имя пользователя.', max_length=100, null=True, verbose_name='ФИО')),
                ('telegram_language', models.CharField(blank=True, help_text="Код языка, используемого пользователем в Telegram (например, 'ru', 'en').", max_length=100, null=True, verbose_name='Язык')),
                ('email', models.EmailField(blank=True, help_text='Email пользователя.', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Телефон пользователя в формате +79991234567.', max_length=16, null=True, verbose_name='Телефон')),
                ('is_active_in_telegram', models.BooleanField(default=False, help_text='Отметьте, если пользователь активен в Telegram.', verbose_name='Пользователь активный в телеграм?')),
                ('cyber_link', models.URLField(blank=True, help_text='Ссылка, которая будет открываться при нажатии на кнопку.', max_length=5000, null=True, verbose_name='Ссылка для кнопки')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-адрес пользователя.', null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, help_text='Информация о браузере и устройстве пользователя.', null=True, verbose_name='User Agent')),
                ('city', models.CharField(blank=True, help_text='Город пользователя.', max_length=100, null=True, verbose_name='Город')),
                ('timezone', models.CharField(blank=True, help_text="Таймзона пользователя (например, 'UTC+3').", max_length=50, null=True, verbose_name='Таймзона')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время регистрации пользователя в системе.', verbose_name='Дата регистрации')),
                ('activate_start', models.DateTimeField(blank=True, help_text='Дата и время, когда пользователь начал взаимодействие с ботом.', null=True, verbose_name='Дата начала взаимодействия')),
                ('bot', models.ForeignKey(blank=True, help_text='бот, с которым связан пользователь.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurenora.cyberxxbot', verbose_name='Бот')),
                ('country', models.ForeignKey(blank=True, help_text='Страна пользователя.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurenora.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': '️☠️ Пользователь',
                'verbose_name_plural': '☠️ Пользователи',
                'ordering': ['-registration_date', 'username'],
                'indexes': [models.Index(fields=['telegram_user_id'], name='idx_telgrm_uid'), models.Index(fields=['node_id'], name='idx_nodeid'), models.Index(fields=['is_active_in_telegram'], name='idx_is_active'), models.Index(fields=['bot'], name='idx_bot'), models.Index(fields=['country'], name='idx_country'), models.Index(fields=['registration_date'], name='idx_reg_date')],
            },
        ),
    ]
