# Generated by Django 5.2.6 on 2025-09-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurenora', '0002_remove_landingpage_bots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyberxxbot',
            old_name='pwa_description_url',
            new_name='description_url',
        ),
        migrations.RenameField(
            model_name='cyberxxbot',
            old_name='pwa_open_delay',
            new_name='open_delay',
        ),
    ]
